services:
  back:
    build: ./back
    environment:
      VALLET_TODAY: "2026-10-12"
    ports:
      - "8000:8000"

  web:
    build: ./web
    ports:
      - "3000:3000"
    depends_on:
      - back
